[build]
builder = "NIXPACKS"
buildCommand = "apt-get install -y fonts-noto fonts-noto-cjk fontconfig && fc-cache -fv && npm install"

[deploy]
startCommand = "node index.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ALWAYS"
